// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/commander-dashboard/App.tsx": () => import("../components/mockups/commander-dashboard/App.tsx"),
  "./components/mockups/commander-dashboard/Current.tsx": () => import("../components/mockups/commander-dashboard/Current.tsx"),
  "./components/mockups/commander-dashboard/components/LiveMonitoringPanel.tsx": () => import("../components/mockups/commander-dashboard/components/LiveMonitoringPanel.tsx")
};
